export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_ONE_ERROR = 'CLEAR_ONE_ERROR';

export const GET_SUBMISSIONS_START = 'GET_SUBMISSIONS_START';
export const GET_SUBMISSIONS_END = 'GET_SUBMISSIONS_END';

export const SUBMIT_SUBMISSION_START = 'SUBMIT_SUBMISSION_START';
export const SUBMIT_SUBMISSION_END = 'SUBMIT_SUBMISSION_END';
