export const GET_SUBMISSIONS_START = 'GET_SUBMISSIONS_START';
export const GET_SUBMISSIONS_END = 'GET_SUBMISSIONS_END';

export const CREATE_SUBMISSION_START = 'CREATE_SUBMISSION_START';
export const CREATE_SUBMISSION_END = 'CREATE_SUBMISSION_END';
